FROM ubuntu:trusty

RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y software-properties-common && \
  apt-get install -y byobu curl git htop man unzip vim wget && \
  rm -rf /var/lib/apt/lists/*

CMD apt-get install gcc48
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN sh run_little.sh
CMD ["./myapp"]